### ISSUE TITLE
Support storing inside Kestra's internal storage

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-elasticsearch#3]
### Feature description

At least for the Search and Request tasks.

The Scroll task already allows this but using a Scroll query wich is not always a good idea (and is deprecated).

**Comment by madisonb** [comment]
I will also add that the search output currently creates a row for each key (and path) within the json structure returned by the Elasticsearch query. A large number of objects, or objects with a large number of keys can easily create 100k rows of "outputs".

Here's a simple example of 90k outputs just for a simple query I ran in my cluster.

In my case, I would rather the entire document be stored as a single kestra URI, and let me use other logic to loop and parse through the rows.

<img width="350" alt="image" src="https://github.com/kestra-io/plugin-elasticsearch/assets/3504194/2704e379-105f-46ef-9e54-00ca7ba1e83d">
